services:
  app:
    image: xiaoman1221/hitokotogo:latest
    container_name: hitokotogo-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      SENTENCES_URL: "https://sentences-bundle.hitokoto.cn"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hitokotogo-redis
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data:
